stages:
  - validate
  - build

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_DRIVER: overlay2

# ----------------------------------------
# Validate Python backend
# ----------------------------------------

validate_backend:
  stage: validate
  image: python:3.12-slim

  script:
    - python --version
    - pip install --no-cache-dir -r backend/requirements.txt
    - python -m compileall backend

# ----------------------------------------
# Build Backend Docker Image
# ----------------------------------------

build_backend:
  stage: build
  image: docker:27-cli

  services:
    - name: docker:27-dind
      alias: docker

  script:
    - docker version
    - docker build -t devops-task-manager-backend:$CI_COMMIT_SHORT_SHA ./backend

# ----------------------------------------
# Build Frontend Docker Image
# ----------------------------------------

build_frontend:
  stage: build
  image: docker:27-cli

  services:
    - name: docker:27-dind
      alias: docker

  script:
    - docker version
    - docker build -t devops-task-manager-frontend:$CI_COMMIT_SHORT_SHA ./frontend
